apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: course-suggestion
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "2453"
  POSTGRES_DB: Course-Suggestion-App
